export const technicalList = [
  {
    title: "Lazada Seller Campaign (促销互动移动端)",
    floor: 1,
    gridArea: "r0c0/r0c1",
    url: "",
    implement: true,
  },
  {
    title: "Lazada Seller Affiliate (卖家倡导计划) 移动端",
    floor: 1,
    gridArea: "r0c2/r0c3",
    url: "",
    implement: true,
  },
  {
    title: "Lazada Seller Affiliate (卖家倡导计划) PC端",
    floor: 1,
    gridArea: "r1c0/r1c1",
    url: "",
    implement: true,
  },
  {
    title: "Merlion-UI 组件库",
    floor: 1,
    gridArea: "r1c2",
    url: "",
    implement: true,
  },
  {
    title: "Admin 游戏运营平台",
    floor: 1,
    gridArea: "r1c3",
    url: "",
    implement: true,
  },
  {
    title: "天燕监控系统",
    floor: 1,
    gridArea: "r2c0",
    url: "",
    implement: true,
  },
  {
    title: "互娱财务系统",
    floor: 1,
    gridArea: "r2c1",
    url: "",
    implement: true,
  },
  {
    title: "图片资源管理系统",
    floor: 1,
    gridArea: "r2c2",
    url: "",
    implement: true,
  },
  {
    title: "互娱打包系统",
    floor: 1,
    gridArea: "r2c3",
    url: "",
    implement: true,
  },
  {
    title: "互娱游戏基础库",
    floor: 1,
    gridArea: "r3c0",
    url: "",
    implement: true,
  },
  {
    title: "One系统",
    floor: 1,
    gridArea: "r3c1",
    url: "",
    implement: true,
  },

  {
    title: "仓颉业务中台",
    floor: 1,
    gridArea: "r3c2",
    url: "",
    implement: true,
  },

  {
    title: "搜索服务化管理中台",
    floor: 1,
    gridArea: "r3c3",
    url: "",
    implement: true,
  },

  {
    title: "爬虫调度平台",
    floor: 1,
    gridArea: "r4c0",
    url: "",
    implement: true,
  },
  {
    title: "爬虫标注平台",
    floor: 1,
    gridArea: "r4c1",
    url: "",
    implement: true,
  },

  {
    title: "爬虫种子管理平台",
    floor: 1,
    gridArea: "r4c2",
    url: "",
    implement: true,
  },

  {
    title: "UED应用部署中台",
    floor: 1,
    gridArea: "r4c3",
    url: "",
    implement: true,
  },
  {
    title: "医鹿病友社区H5应用",
    floor: 1,
    gridArea: "r5c0",
    url: "",
    implement: true,
  },

  {
    title: "WMS 仓储管理系统",
    floor: 1,
    gridArea: "r5c2",
    url: "",
    implement: true,
  },
  {
    title: "渡鸦可视化搭建平台",
    floor: 1,
    gridArea: "r5c3/r6c3",
    url: "",
    implement: true,
  },
  {
    title: "样本库管理平台",
    floor: 1,
    gridArea: "r5c1/r6c1",
    url: "",
    implement: true,
  },
  {
    title: "rhino-ui 业务组件库",
    floor: 1,
    gridArea: "r6c0",
    url: "",
    implement: true,
  },
  {
    title: "node 爬虫",
    floor: 1,
    gridArea: "r6c2",
    url: "",
    implement: true,
  },
];
