export const BACKGROUND_COLOR = [
  // "#7A2B1E",
  // "#269695",
  // "#389960",
  // "#3FAA69",
  // "#AAD871",
  // "#36287A",
  "rgba(0, 127, 127, 0.7)",
  "rgb(38, 150, 149, 0.7)",
  "rgb(56, 153, 96, 0.7)",
  "rgb(54, 40, 122, 0.7)",
  "rgb(112, 145, 82, 0.7)",
  // "rgb(122, 43, 30, 0.7)",
];

export const BACKGROUND_COLOR_HOVER = [
  // "#7A2B1E",
  // "#269695",
  // "#389960",
  // "#3FAA69",
  // "#AAD871",
  // "#36287A",
  "rgba(0, 127, 127, 1)",
  "rgb(38, 150, 149, 1)",
  "rgb(56, 153, 96, 1)",
  "rgb(54, 40, 122, 1)",
  "rgb(112, 145, 82, 1)",
  // "rgb(122, 43, 30, 1)",
];

export const BORDER_COLOR = [
  "rgba(127,255,255,0.7)",
  "rgb(54, 211, 209, 0.7)",
  "rgb(80, 219, 138, 0.7)",
  "rgb(95, 70, 217, 0.7)",
  "rgb(170, 219, 125, .7)",
];

export const BORDER_COLOR_HOVER = [
  "rgba(127,255,255,1)",
  "rgb(54, 211, 209, 1)",
  "rgb(80, 219, 138, 1)",
  "rgb(95, 70, 217, 1)",
  "rgb(170, 219, 125, 1)",
];

export const technicalList = [
  {
    title: "r0c0",
    floor: 1,
    gridArea: "r0c0",
    url: "",
    implement: true,
  },
  {
    title: "r0c1",
    floor: 1,
    gridArea: "r0c1",
    url: "",
    implement: true,
  },
  {
    title: "r0c2/r0c3",
    floor: 1,
    gridArea: "r0c2/r0c3",
    url: "",
    implement: true,
  },
  {
    title: "行业洞察",
    floor: 2,
    gridArea: "r1c0",
    "//url": "https://yuque.antfin.com/aligames_dt/ww6sdg",
    "//description": "发现游戏行业热点和动向、发现新游",
    "//detail":
      "基于外部市场数据和自身数据的深入分析，建立游戏基础信息数据库，具备基础的游戏基础信息、舆情、用户画像等分析洞察能力，为新游分析决策提供数据支持",
    implement: false,
  },
  {
    title: "r1c1",
    floor: 1,
    gridArea: "r1c1",
    url: "",
    implement: true,
  },
  {
    title: "r1c2",
    floor: 1,
    gridArea: "r1c2",
    url: "",
    implement: true,
  },
  {
    title: "r1c3",
    floor: 1,
    gridArea: "r1c3",
    url: "",
    implement: true,
  },
  {
    title: "r2c0",
    floor: 1,
    gridArea: "r2c0",
    url: "",
    implement: true,
  },
  {
    title: "r2c1",
    floor: 1,
    gridArea: "r2c1",
    url: "",
    implement: true,
  },
  {
    title: "r2c2/r2c3",
    floor: 1,
    gridArea: "r2c2/r2c3",
    url: "",
    implement: true,
  },

  {
    title: "r3c0/r4c0",
    floor: 2,
    gridArea: "r3c0/r4c0",
    url: "https://yuque.antfin.com/larva-team/raven",
    description: "互娱统一搭建平台",
    detail: "可视化搭建，一分钟完成站点上线，海内外业务同时发布。",
    implement: true,
  },
  {
    title: "r3c1/r4c1",
    floor: 2,
    gridArea: "r3c1/r4c1",
    url: "https://yuque.antfin.com/larva-team/raven",
    description: "互娱统一搭建平台",
    detail: "可视化搭建，一分钟完成站点上线，海内外业务同时发布。",
    implement: true,
  },
  {
    title: "r3c2/r3c3",
    floor: 2,
    gridArea: "r3c2/r3c3",
    url: "https://yuque.antfin.com/aligames_dt/eeb9p7/ioo3ut",
    description: "犀量发行平台",
    detail:
      "犀量发行平台是支持多媒体多账户一站式智能广告投放的数据平台，通过大数据平台能力与多个投放媒体深度打通，致力于为游戏发行提供高效可靠的一站式智能广告投放服务",
    implement: true,
  },
  {
    title: "r4c2/r4c3",
    floor: 1,
    gridArea: "r4c2/r4c3",
    url: "",
    implement: true,
  },

  {
    title: "r5c0/r5c1/r6c0/r6c1",
    floor: 2,
    gridArea: "r5c0/r5c1/r6c0/r6c1",
    url: "https://yuque.antfin.com/larva-team/raven",
    description: "互娱统一搭建平台",
    detail: "可视化搭建，一分钟完成站点上线，海内外业务同时发布。",
    implement: true,
  },
  {
    title: "r5c2/r6c2",
    floor: 2,
    gridArea: "r5c2/r6c2",
    url: "https://yuque.antfin.com/aligames_dt/eeb9p7/ioo3ut",
    description: "犀量发行平台",
    detail:
      "犀量发行平台是支持多媒体多账户一站式智能广告投放的数据平台，通过大数据平台能力与多个投放媒体深度打通，致力于为游戏发行提供高效可靠的一站式智能广告投放服务",
    implement: true,
  },
  {
    title: "r5c3",
    floor: 1,
    gridArea: "r5c3",
    url: "",
    implement: true,
  },

  {
    title: "r6c3",
    floor: 1,
    gridArea: "r6c3",
    url: "",
    implement: true,
  },

  {
    title: "r7c0",
    floor: 1,
    gridArea: "r7c0",
    url: "",
    implement: true,
  },
  {
    title: "r7c1",
    floor: 1,
    gridArea: "r7c1",
    url: "",
    implement: true,
  },
  {
    title: "r7c2",
    floor: 1,
    gridArea: "r7c2",
    url: "",
    implement: true,
  },
  {
    title: "r7c3",
    floor: 1,
    gridArea: "r7c3",
    url: "",
    implement: true,
  },

  {
    title: "r8c0",
    floor: 1,
    gridArea: "r8c0",
    url: "",
    implement: true,
  },
  {
    title: "r8c1",
    floor: 1,
    gridArea: "r8c1",
    url: "",
    implement: true,
  },
  {
    title: "r8c2/r8c3",
    floor: 1,
    gridArea: "r8c2/r8c3",
    url: "",
    implement: true,
  },

  {
    title: "r9c0/r9c1",
    floor: 1,
    gridArea: "r9c0/r9c1",
    url: "",
    implement: true,
  },

  {
    title: "r9c2",
    floor: 1,
    gridArea: "r9c2",
    url: "",
    implement: true,
  },
  {
    title: "r9c3",
    floor: 1,
    gridArea: "r9c3",
    url: "",
    implement: true,
  },

  {
    title: "r10c0",
    floor: 1,
    gridArea: "r10c0",
    url: "",
    implement: true,
  },
  {
    title: "r10c1",
    floor: 1,
    gridArea: "r10c1",
    url: "",
    implement: true,
  },
  {
    title: "r10c2",
    floor: 1,
    gridArea: "r10c2",
    url: "",
    implement: true,
  },
  {
    title: "r10c3/r11c3",
    floor: 1,
    gridArea: "r10c3/r11c3",
    url: "",
    implement: true,
  },

  {
    title: "r11c0",
    floor: 1,
    gridArea: "r11c0",
    url: "",
    implement: true,
  },
  {
    title: "r11c1",
    floor: 1,
    gridArea: "r11c1",
    url: "",
    implement: true,
  },
  {
    title: "r11c2",
    floor: 1,
    gridArea: "r11c2",
    url: "",
    implement: true,
  },

  {
    title: "r12c0/r12c1",
    floor: 1,
    gridArea: "r12c0/r12c1",
    url: "",
    implement: true,
  },
  {
    title: "r12c2/r12c3",
    floor: 1,
    gridArea: "r12c2/r12c3",
    url: "",
    implement: true,
  },

  {
    title: "r16c0/r16c1/r16c2/r16c3",
    floor: 1,
    gridArea: "r16c0/r16c1/r16c2/r16c3",
    url: "",
    implement: true,
  },
];
